apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authenticate
spec:
  replicas: 1
  selector:
    matchLabels:
      component: authenticate
  template:
    metadata:
      labels:
        component: authenticate
    spec:
      containers:
      - env:
        - name: SPRING_EUREKA
          value: http://eureka-cluster-ip-service:8761/eureka
        image: asia.gcr.io/indigo-muse-254504/authenticate:1.1.2
        name: authenticate
        ports:
        - containerPort: 80
