spring:
  application:
    name: zuul

server:
  port: 8760

eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA}

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD  
          thread:
            timeoutInMilliseconds: 300000


ribbon:
  ReadTimeout: 300000
  connection-timeout: 300000
  eureka:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'