apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      component: eureka
  template:
    metadata:
      labels:
        component: eureka
    spec:
      containers:
      - env:
        - name: SPRING_EUREKA
          value: http://eureka-cluster-ip-service.default.svc.cluster.local:8761/eureka
        image: asia.gcr.io/carbide-ward-264607/eureka:1.0
        name: eureka
        ports:
        - containerPort: 8761