apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      component: testmanagement
  template:
    metadata:
      labels:
        component: testmanagement
    spec:
      containers:
      - env:
        - name: SPRING_EUREKA
          value: http://eureka-cluster-ip-service:8761/eureka
        image: asia.gcr.io/carbide-ward-264607/test:1.0
        name: testmanagement
        ports:
        - containerPort: 80