apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mailling
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mailling
  template:
    metadata:
      labels:
        component: mailling
    spec:
      containers:
      - env:
        - name: SPRING_EUREKA
          value: http://eureka-cluster-ip-service:8761/eureka
        image: asia.gcr.io/sunny-airfoil-258516/mailling:1.0
        name: mailling
        ports:
        - containerPort: 80
